### ISSUE TITLE
Remove unused code from Issue16

### ISSUE THREAD

**Issue by stephaniaa** [stephaniaa/stephAssignment1#30]

**Comment by edbrax** [comment]
I've got another bloody flat tire with a nail in it. This is like the fifth since I came to Sydney. I think I might have had two in thirty years and over 500,000 km of driving before I came here. Do you think it might be deliberate?

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
Shit, I wouldn’t have thought so - who would do that?!
Do you think it’s someone in your complex?

**Comment by edbrax** [comment]
The tire takes a while to go flat with a nail in it - it could be done at the shops or at uni. Maybe some people just don't like people who drive powerful cars? Or maybe it's a form of sneaky road rage, I drive aggressively and piss someone off who then follows me to the shops or uni? I don't know, but how many times can you pick up a nail that just accidentally gets driven into the tire at 90 degrees like this? Maybe tire places pay people to spike expensive tires in Sydney. Anything is possible in this town. But seriously, 2 flat tires in 500,000 km vs 5 in 15,000 kms. What are the odds?

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary

**Comment by stephaniaa** [comment]
So you’ve had a nail in your tyre 5 times in syd? In your old car as well or just this new one?
Yea neither explanation makes sense to me!

**Comment by edbrax** [comment]
The other 4 were in the old car.

Ed Brackenreg

Engineering Student, School of Electrical and Information Engineering
THE UNIVERSITY OF SYDNEY
Mob: 0414 943 642
E ebra7152@uni.sydney.edu.aumailto:ebra7152@uni.sydney.edu.au https://outlook.office365.com/owa/#path=/mail https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f | W http://sydney.edu.auhttps://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f
https://ch1prd0102.outlook.com/owa/redir.aspx?C=mMwIKfJ8nUiLVXyaF-Wp1HOZtQcX788IWr7QLis5_VSHe8nvj3YWZtY5cONeZhL0EoWkyKx-j_k.&URL=http%3a%2f%2fsydney.edu.au%2f

---

This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited. If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this e-mail if necessary
